"use client"

import { DashboardHeader } from "@/components/dashboard-header"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Search, FileText, Loader2, Smile, Meh, Frown, BarChart3, Users, TrendingUp } from "lucide-react"
import { useState, useEffect, useRef } from "react"
import { useRouter } from "next/navigation"
import { toast } from "@/components/ui/use-toast"
import { getCustomerNameByJobId, getPhoneNumberByJobId } from "@/lib/call-memory"
import { saveEvaluationTranscript, getTranscriptsByEmployeeId } from "@/lib/evaluation-storage"

interface CallRecord {
  id: string
  customerName: string
  phoneNumber: string
  date: string
  time: string
  duration: string
  status: string
  type: string
  hasReport: boolean
  score?: number
  mood?: string
  notes?: string
}

interface CallReport {
  id: string
  notes: string
}

interface FullEvaluation {
  id: string
  employeeId: string
  employeeName: string
  employeePosition: string
  totalCalls: number
  completedCalls: number
  reportsGenerated: number
  status: "in-progress" | "ready" | "completed"
  callRecords: string[]
  evaluation?: string
  metrics?: {
    overallScore: number | null
    sentiment: string
  }
  generatedAt?: string
}

const CUSTOMER_MOODS = {
  happy: { label: "Happy", color: "bg-green-500/20 text-green-600 border-green-500/30" },
  satisfied: { label: "Satisfied", color: "bg-blue-500/20 text-blue-600 border-blue-500/30" },
  neutral: { label: "Neutral", color: "bg-gray-500/20 text-gray-600 border-gray-500/30" },
  frustrated: { label: "Frustrated", color: "bg-orange-500/20 text-orange-600 border-orange-500/30" },
  angry: { label: "Angry", color: "bg-red-500/20 text-red-600 border-red-500/30" },
}

export default function CustomerRecordsPage() {
  const [searchQuery, setSearchQuery] = useState("")
  const [statusFilter, setStatusFilter] = useState("all")
  const [sortFilter, setSortFilter] = useState("newest")
  const [records, setRecords] = useState<CallRecord[]>([])
  const [filteredRecords, setFilteredRecords] = useState<CallRecord[]>([])
  const [isLoading, setIsLoading] = useState(true)
  const [generatingReportId, setGeneratingReportId] = useState<string | null>(null)
  const [editingNotes, setEditingNotes] = useState<{ id: string; notes: string } | null>(null)
  const [isNotesDialogOpen, setIsNotesDialogOpen] = useState(false)
  const [fullEvaluations, setFullEvaluations] = useState<FullEvaluation[]>([])
  const [generatingFullEvalId, setGeneratingFullEvalId] = useState<string | null>(null)
  const autoGeneratedReports = useRef(new Set<string>())
  const router = useRouter()

  useEffect(() => {
    fetchCustomerRecords()
  }, [])

  useEffect(() => {
    const savedRecords = localStorage.getItem("customer-records")
    if (savedRecords) {
      try {
        const parsed = JSON.parse(savedRecords)
        setRecords((current) => {
          const merged = [...current]
          parsed.forEach((saved: CallRecord) => {
            const index = merged.findIndex((r) => r.id === saved.id)
            if (index >= 0) {
              merged[index] = { ...merged[index], ...saved }
            }
          })
          return merged
        })
      } catch (error) {
        console.error("[v0] Error loading saved records:", error)
      }
    }
  }, [])

  useEffect(() => {
    if (records.length > 0) {
      const dataToSave = records.map((r) => ({
        id: r.id,
        hasReport: r.hasReport,
        score: r.score,
        mood: r.mood,
        notes: r.notes,
      }))
      localStorage.setItem("customer-records", JSON.stringify(dataToSave))
    }
  }, [records])

  useEffect(() => {
    updateFullEvaluations()
  }, [records])

  async function fetchCustomerRecords() {
    try {
      const savedReportsJSON = localStorage.getItem("call-reports")
      const savedReports = savedReportsJSON ? JSON.parse(savedReportsJSON) : []

      console.log("[v0] Fetched reports from localStorage:", savedReports.length)

      const response = await fetch("/api/hamsa/jobs?limit=100")
      if (response.ok) {
        const data = await response.json()
        const jobs = data.data?.jobs || []

        const transformedRecords = jobs
          .map((job: any) => {
            const customerNameFromMemory = getCustomerNameByJobId(job.id)
            const phoneNumberFromMemory = getPhoneNumberByJobId(job.id)

            if (!customerNameFromMemory) {
              return null
            }

            const startTime = new Date(job.createdAt)
            const durationInSeconds = job.duration || 0
            const minutes = Math.floor(durationInSeconds / 60)
            const seconds = durationInSeconds % 60

            let callStatus = "in-progress"
            const hamsaStatus = (job.status || "").toUpperCase()

            if (hamsaStatus === "COMPLETED" || hamsaStatus === "SUCCEEDED") {
              callStatus = "completed"
            } else if (hamsaStatus === "FAILED" || hamsaStatus === "ERROR") {
              callStatus = "failed"
            } else if (
              hamsaStatus === "NO_ANSWER" ||
              hamsaStatus === "NO-ANSWER" ||
              hamsaStatus === "NOANSWER" ||
              hamsaStatus === "UNANSWERED"
            ) {
              callStatus = "no-answer"
            } else if (hamsaStatus === "CANCELLED" || hamsaStatus === "CANCELED") {
              callStatus = "cancelled"
            } else if (hamsaStatus === "PENDING" || hamsaStatus === "QUEUED") {
              callStatus = "pending"
            } else if (
              hamsaStatus === "IN-PROGRESS" ||
              hamsaStatus === "IN_PROGRESS" ||
              hamsaStatus === "RUNNING" ||
              hamsaStatus === "ACTIVE"
            ) {
              callStatus = "in-progress"
            }

            const localReport = savedReports.find((r: any) => r.id === job.id || r.callId === job.id)
            const reportExists = !!localReport
            const reportData = localReport

            return {
              id: job.id,
              customerName: customerNameFromMemory,
              phoneNumber: phoneNumberFromMemory || job.customer?.number || "N/A",
              date: startTime.toISOString().split("T")[0],
              time: startTime.toTimeString().slice(0, 5),
              duration: `${minutes.toString().padStart(2, "0")}:${seconds.toString().padStart(2, "0")}`,
              status: callStatus,
              type: "outbound",
              hasReport: reportExists,
              score: reportData?.analysis?.customerOverallScore,
              mood: reportData?.analysis?.customerMood,
              notes: reportData?.notes || "",
            }
          })
          .filter((record) => record !== null)

        const localRecords = savedReports
          .map((report: any) => {
            if (transformedRecords.find((r) => r.id === report.id)) {
              return null
            }

            const duration = report.duration || "0:00"

            return {
              id: report.id,
              customerName: report.customerName || "Unknown",
              phoneNumber: report.phoneNumber || "N/A",
              date: new Date(report.createdAt).toISOString().split("T")[0],
              time: new Date(report.createdAt).toTimeString().slice(0, 5),
              duration: duration,
              status: report.status || "completed",
              type: "outbound",
              hasReport: true,
              score: report.analysis?.customerOverallScore,
              mood: report.analysis?.customerMood,
              notes: report.notes || "",
            }
          })
          .filter((record) => record !== null)

        setRecords([...transformedRecords, ...localRecords])
        setFilteredRecords([...transformedRecords, ...localRecords])
      }
    } catch (error) {
      console.error("[v0] Error fetching customer records:", error)
    } finally {
      setIsLoading(false)
    }
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "completed":
        return <Smile className="h-4 w-4 text-success" />
      case "failed":
        return <Frown className="h-4 w-4 text-destructive" />
      case "no-answer":
        return <Meh className="h-4 w-4 text-warning" />
      case "cancelled":
        return <Frown className="h-4 w-4 text-muted-foreground" />
      case "pending":
        return <Loader2 className="h-4 w-4 text-warning" />
      case "in-progress":
        return <Loader2 className="h-4 w-4 text-primary animate-spin" />
      default:
        return <Loader2 className="h-4 w-4 text-muted-foreground" />
    }
  }

  const getStatusBadge = (status: string) => {
    const variants: Record<string, string> = {
      completed: "bg-success/20 text-success border-success/30",
      failed: "bg-destructive/20 text-destructive border-destructive/30",
      "no-answer": "bg-warning/20 text-warning border-warning/30",
      cancelled: "bg-muted text-muted-foreground border-muted",
      pending: "bg-warning/20 text-warning border-warning/30",
      "in-progress": "bg-primary/20 text-primary border-primary/30",
    }
    return variants[status] || "bg-muted text-muted-foreground border-muted"
  }

  const statusCounts = {
    total: records.length,
    completed: records.filter((r) => r.status === "completed").length,
    inProgress: records.filter((r) => r.status === "in-progress" || r.status === "pending").length,
    urgent: records.filter((r) => r.status === "failed" || r.status === "no-answer").length,
  }

  useEffect(() => {
    const autoGenerateReports = async () => {
      for (const record of records) {
        if (
          record.status === "completed" &&
          !record.hasReport &&
          !autoGeneratedReports.current.has(record.id) &&
          !generatingReportId
        ) {
          console.log("[v0] Auto-generating report for completed call:", record.id)
          autoGeneratedReports.current.add(record.id)

          await handleGenerateReport(record.id, record)

          break
        }
      }
    }

    if (records.length > 0) {
      autoGenerateReports()
    }
  }, [records, generatingReportId])

  useEffect(() => {
    let filtered = [...records]

    // Apply search filter
    if (searchQuery) {
      filtered = filtered.filter(
        (record) =>
          record.customerName.toLowerCase().includes(searchQuery.toLowerCase()) ||
          record.phoneNumber.includes(searchQuery),
      )
    }

    // Apply status filter
    if (statusFilter !== "all") {
      filtered = filtered.filter((record) => record.status === statusFilter)
    }

    // Apply sort
    filtered.sort((a, b) => {
      const dateA = new Date(`${a.date} ${a.time}`).getTime()
      const dateB = new Date(`${b.date} ${b.time}`).getTime()
      return sortFilter === "newest" ? dateB - dateA : dateA - dateB
    })

    setFilteredRecords(filtered)
  }, [records, searchQuery, statusFilter, sortFilter])

  const handleGenerateReport = async (callId: string, recordData?: CallRecord) => {
    setGeneratingReportId(callId)
    try {
      console.log("[v0] Generating report for:", callId, "with record data:", recordData)

      const response = await fetch("/api/reports/generate", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ callId }),
      })

      if (response.ok) {
        const report = await response.json()
        console.log("[v0] Generated report:", report)

        const completeReport = {
          ...report,
          customerName: recordData?.customerName || report.customerName || getCustomerNameByJobId(callId) || "Unknown",
          phoneNumber: recordData?.phoneNumber || report.phoneNumber || getPhoneNumberByJobId(callId) || "N/A",
          duration: recordData?.duration || report.duration || "0:00",
          status: "completed",
        }

        console.log("[v0] Complete report with merged data:", completeReport)

        const existingReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
        const updatedReports = [completeReport, ...existingReports.filter((r: any) => r.id !== callId)]
        localStorage.setItem("call-reports", JSON.stringify(updatedReports))
        console.log("[v0] Report saved to localStorage successfully")

        const moodFromAnalysis =
          completeReport.analysis?.customerMood ||
          determineMoodFromScore(completeReport.analysis?.customerOverallScore || 5)

        setRecords((current) =>
          current.map((r) =>
            r.id === callId
              ? {
                  ...r,
                  customerName: completeReport.customerName,
                  phoneNumber: completeReport.phoneNumber,
                  duration: completeReport.duration,
                  status: "completed",
                  hasReport: true,
                  score: completeReport.analysis?.customerOverallScore,
                  mood: moodFromAnalysis,
                }
              : r,
          ),
        )

        router.push(`/reports/${callId}`)
      } else {
        const errorText = await response.text()
        console.error("[v0] Failed to generate report:", errorText)
        alert("Failed to generate report. Please try again.")
      }
    } catch (error) {
      console.error("[v0] Error generating report:", error)
      alert("Error generating report. Please try again.")
    } finally {
      setGeneratingReportId(null)
    }
  }

  const determineMoodFromScore = (score: number): string => {
    if (score >= 9) return "happy"
    if (score >= 7) return "satisfied"
    if (score >= 5) return "neutral"
    if (score >= 3) return "frustrated"
    return "angry"
  }

  const handleNotesUpdate = (callId: string, notes: string) => {
    setEditingNotes({ id: callId, notes })
    setIsNotesDialogOpen(true)
  }

  const handleSaveNotes = async () => {
    if (!editingNotes) return

    try {
      const existingReports = JSON.parse(localStorage.getItem("call-reports") || "[]")
      const updatedReports = existingReports.map((r: any) =>
        r.id === editingNotes.id || r.callId === editingNotes.id ? { ...r, notes: editingNotes.notes } : r,
      )
      localStorage.setItem("call-reports", JSON.stringify(updatedReports))
      console.log("[v0] Notes saved to localStorage successfully")

      setRecords((current) => current.map((r) => (r.id === editingNotes.id ? { ...r, notes: editingNotes.notes } : r)))

      setIsNotesDialogOpen(false)
      setEditingNotes(null)
    } catch (error) {
      console.error("[v0] Error saving notes:", error)
      alert("Failed to save notes. Please try again.")
    }
  }

  const loadRecords = () => {
    fetchCustomerRecords()
  }

  const updateFullEvaluations = () => {
    const metaStored = localStorage.getItem("evaluation_metadata")
    if (!metaStored) {
      setFullEvaluations([])
      return
    }

    let evaluationData = JSON.parse(metaStored)

    // Old structure: key is callId, has employeeId inside
    // New structure: key is employeeId, has callIds array
    let needsMigration = false
    const migratedData: any = {}

    Object.keys(evaluationData).forEach((key) => {
      const metadata = evaluationData[key]

      // Check if this is old structure (no callIds array but has employeeId)
      if (metadata.employeeId && (!metadata.callIds || !Array.isArray(metadata.callIds))) {
        needsMigration = true
        const employeeId = metadata.employeeId

        // Initialize employee entry if doesn't exist
        if (!migratedData[employeeId]) {
          migratedData[employeeId] = {
            employeeId: employeeId,
            employeeName: metadata.employeeName,
            employeePosition: metadata.employeePosition,
            callIds: [],
            createdAt: metadata.createdAt || new Date().toISOString(),
          }
        }

        // Add this callId to the employee's callIds array
        if (!migratedData[employeeId].callIds.includes(key)) {
          migratedData[employeeId].callIds.push(key)
        }

        console.log(`[v0] Migrated old metadata: ${key} → employee ${employeeId}`)
      } else if (metadata.callIds && Array.isArray(metadata.callIds)) {
        // This is already new structure, keep it
        migratedData[key] = metadata
      }
    })

    // Save migrated data if changes were made
    if (needsMigration) {
      localStorage.setItem("evaluation_metadata", JSON.stringify(migratedData))
      evaluationData = migratedData
      console.log("[v0] Metadata migration completed")
    }

    const employeeGroups: { [key: string]: FullEvaluation } = {}

    console.log("[v0] Evaluation metadata:", evaluationData)

    Object.keys(evaluationData).forEach((key) => {
      const metadata = evaluationData[key]

      // Skip entries that don't have callIds array (old structure)
      if (!metadata.callIds || !Array.isArray(metadata.callIds)) {
        console.log(`[v0] Skipping invalid metadata entry: ${key} (no callIds array)`)
        return
      }

      const employeeId = metadata.employeeId
      const employeeName = metadata.employeeName
      const employeePosition = metadata.employeePosition

      if (!employeeId || !employeeName) {
        console.log(`[v0] Skipping metadata entry: ${key} (missing employeeId or employeeName)`)
        return
      }

      // Create employee group if it doesn't exist
      if (!employeeGroups[employeeId]) {
        employeeGroups[employeeId] = {
          id: employeeId,
          employeeId,
          employeeName,
          employeePosition,
          totalCalls: 0,
          completedCalls: 0,
          reportsGenerated: 0,
          callRecords: [],
          status: "in-progress",
        }
      }

      metadata.callIds.forEach((callId: string) => {
        if (!employeeGroups[employeeId].callRecords.includes(callId)) {
          employeeGroups[employeeId].callRecords.push(callId)
          employeeGroups[employeeId].totalCalls++

          // Check if this call is completed and has a report
          const callRecord = records.find((r) => r.id === callId)
          if (callRecord) {
            console.log(`[v0] Call ${callId} status: ${callRecord.status}, hasReport: ${callRecord.hasReport}`)

            if (callRecord.status === "completed") {
              employeeGroups[employeeId].completedCalls++
            }
            if (callRecord.hasReport) {
              employeeGroups[employeeId].reportsGenerated++

              const reportStored = localStorage.getItem("call-reports")
              if (reportStored) {
                const reports = JSON.parse(reportStored)
                const report = reports.find((r: any) => r.id === callId)

                if (report && report.transcript) {
                  console.log(`[v0] Auto-saving transcript for call ${callId}`)

                  // Save to evaluation storage
                  const transcriptStored = localStorage.getItem("evaluation_transcripts")
                  const transcripts = transcriptStored ? JSON.parse(transcriptStored) : {}

                  if (!transcripts[employeeId]) {
                    transcripts[employeeId] = []
                  }

                  // Check if transcript already exists
                  const existingIndex = transcripts[employeeId].findIndex((t: any) => t.callId === callId)

                  if (existingIndex === -1) {
                    transcripts[employeeId].push({
                      callId: callId,
                      transcript: report.transcript,
                      contactName: report.customerName || "Unknown",
                      duration: report.duration || 0,
                      createdAt: report.createdAt || new Date().toISOString(),
                    })

                    localStorage.setItem("evaluation_transcripts", JSON.stringify(transcripts))
                    console.log(`[v0] Transcript saved for employee ${employeeName}, call ${callId}`)
                  }
                }
              }
            }
          }
        }
      })
    })

    console.log("[v0] Employee groups:", employeeGroups)

    const existingEvals = localStorage.getItem("full_evaluations")
    const existingEvalsData = existingEvals ? JSON.parse(existingEvals) : {}

    const evaluations = Object.values(employeeGroups).map((group: any) => {
      let status: "in-progress" | "ready" | "completed" = "in-progress"

      console.log(
        `[v0] Employee ${group.employeeName}: ${group.completedCalls}/${group.totalCalls} completed, ${group.reportsGenerated}/${group.totalCalls} reports`,
      )

      if (group.completedCalls === group.totalCalls && group.reportsGenerated === group.totalCalls) {
        status = "ready"
      }

      if (existingEvalsData[group.employeeId]) {
        return {
          ...group,
          status: "completed",
          evaluation: existingEvalsData[group.employeeId].evaluation,
          metrics: existingEvalsData[group.employeeId].metrics,
          generatedAt: existingEvalsData[group.employeeId].generatedAt,
        }
      }

      return { ...group, status }
    })

    setFullEvaluations(evaluations)
  }

  const handleGenerateFullEvaluation = async (evaluation: FullEvaluation) => {
    try {
      console.log("[v0] Generating full evaluation for:", evaluation.employeeName)
      console.log("[v0] Employee ID:", evaluation.employeeId)
      console.log("[v0] Call IDs:", evaluation.callRecords)

      const employeeTranscripts = getTranscriptsByEmployeeId(evaluation.employeeId)
      console.log("[v0] Found", employeeTranscripts.length, "transcripts in localStorage")

      const response = await fetch("/api/evaluation/generate-full-report", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          employeeId: evaluation.employeeId,
          employeeName: evaluation.employeeName,
          callIds: evaluation.callRecords,
          transcripts: employeeTranscripts.length > 0 ? employeeTranscripts : null,
        }),
      })

      const data = await response.json()

      if (!data.success) {
        throw new Error(data.error || "Failed to generate evaluation")
      }

      const existingEvals = localStorage.getItem("full_evaluations")
      const evalsData = existingEvals ? JSON.parse(existingEvals) : {}
      evalsData[evaluation.employeeId] = {
        evaluation: data.evaluation,
        metrics: data.metrics,
        generatedAt: data.generatedAt,
      }
      localStorage.setItem("full_evaluations", JSON.stringify(evalsData))

      updateFullEvaluations()

      console.log("[v0] Full evaluation generated and saved successfully")
      toast({
        title: "Evaluation Generated",
        description: `The full evaluation for ${evaluation.employeeName} has been generated successfully.`,
        variant: "success",
      })
    } catch (error) {
      console.error("[v0] Error generating full evaluation:", error)
      toast({
        title: "Error",
        description: `Failed to generate full evaluation for ${evaluation.employeeName}: ${error instanceof Error ? error.message : "Unknown error"}`,
        variant: "destructive",
      })
    } finally {
      setGeneratingFullEvalId(null)
    }
  }

  const handleSaveTranscript = async (callId: string) => {
    try {
      console.log("[v0] Fetching and saving transcript for call:", callId)

      // Get evaluation metadata to find employee info
      const metadata = localStorage.getItem("evaluation_metadata")
      if (!metadata) {
        console.error("[v0] No evaluation metadata found")
        return
      }

      const evaluationData = JSON.parse(metadata)
      const callMetadata = evaluationData[callId]

      if (!callMetadata) {
        console.error("[v0] No metadata found for this call")
        return
      }

      // Fetch transcript from API
      const response = await fetch("/api/hamsa/save-transcript", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          callId,
          employeeId: callMetadata.employeeId,
          employeeName: callMetadata.employeeName,
        }),
      })

      if (!response.ok) {
        throw new Error("Failed to fetch transcript")
      }

      const data = await response.json()

      if (data.success) {
        // Save to localStorage using our utility
        saveEvaluationTranscript(data.data)
        console.log("[v0] Transcript saved successfully for:", callMetadata.employeeName)
      }
    } catch (error) {
      console.error("[v0] Error saving transcript:", error)
    }
  }

  useEffect(() => {
    const autoSaveTranscripts = async () => {
      const metadata = localStorage.getItem("evaluation_metadata")
      if (!metadata) return

      const evaluationData = JSON.parse(metadata)

      for (const record of records) {
        if (record.status === "completed" && record.hasReport) {
          // Find the employee that has this call in their callIds
          let employeeMetadata = null
          let employeeId = null

          for (const [empId, empData] of Object.entries(evaluationData)) {
            const data = empData as any
            if (data.callIds && data.callIds.includes(record.id)) {
              employeeMetadata = data
              employeeId = empId
              break
            }
          }

          if (employeeMetadata && employeeId) {
            // Check if transcript already saved
            const existing = getTranscriptsByEmployeeId(employeeId)
            const alreadySaved = existing.some((t) => t.callId === record.id)

            if (!alreadySaved) {
              console.log("[v0] Auto-saving transcript for completed call:", record.id)
              try {
                // Fetch transcript from API
                const response = await fetch("/api/hamsa/save-transcript", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    callId: record.id,
                    employeeId: employeeId,
                    employeeName: (employeeMetadata as any).employeeName,
                  }),
                })

                if (response.ok) {
                  const data = await response.json()
                  if (data.success) {
                    saveEvaluationTranscript(data.data)
                    console.log("[v0] Transcript saved successfully for:", (employeeMetadata as any).employeeName)
                  }
                }
              } catch (error) {
                console.error("[v0] Error auto-saving transcript:", error)
              }
            }
          }
        }
      }
    }

    if (records.length > 0) {
      autoSaveTranscripts()
    }
  }, [records])

  const handleViewFullEvaluation = (evaluation: FullEvaluation) => {
    router.push(`/evaluations/${evaluation.employeeId}`)
  }

  const completedCount = records.filter((r) => r.status === "completed").length
  const inProgressCount = records.filter((r) => r.status === "in-progress" || r.status === "pending").length
  const urgentCount = records.filter((r) => r.status === "failed").length

  return (
    <div className="flex h-screen flex-col bg-background">
      <DashboardHeader />
      <main className="flex-1 overflow-y-auto p-6">
        <div className="mb-6">
          <h1 className="font-sans text-3xl font-bold text-foreground">Customer Records</h1>
          <p className="mt-1 font-sans text-sm text-muted-foreground">
            View and manage all customer call interactions and evaluations
          </p>
        </div>

        {fullEvaluations.length > 0 && (
          <Card className="mb-6 border-primary/20 bg-primary/5">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <TrendingUp className="h-5 w-5" />
                Full Employee Evaluations ({fullEvaluations.length})
              </CardTitle>
              <CardDescription>Comprehensive evaluations combining all feedback for each employee</CardDescription>
            </CardHeader>
            <CardContent>
              <div className="space-y-3">
                {fullEvaluations.map((evaluation) => (
                  <div
                    key={evaluation.id}
                    className="flex items-center justify-between p-4 bg-background border border-border rounded-lg"
                  >
                    <div className="flex-1">
                      <div className="flex items-center gap-3 mb-2">
                        <h3 className="font-semibold text-lg">{evaluation.employeeName}</h3>
                        <Badge
                          variant="outline"
                          className={
                            evaluation.status === "completed"
                              ? "bg-success/20 text-success border-success/30"
                              : evaluation.status === "ready"
                                ? "bg-primary/20 text-primary border-primary/30"
                                : "bg-warning/20 text-warning border-warning/30"
                          }
                        >
                          {evaluation.status === "completed"
                            ? "Evaluation Complete"
                            : evaluation.status === "ready"
                              ? "Ready for Evaluation"
                              : "In Progress"}
                        </Badge>
                        {evaluation.metrics?.overallScore && (
                          <Badge variant="outline" className="bg-blue-500/20 text-blue-600 border-blue-500/30">
                            Score: {evaluation.metrics.overallScore}/10
                          </Badge>
                        )}
                      </div>
                      <div className="flex items-center gap-6 text-sm text-muted-foreground">
                        <span>
                          Calls: {evaluation.completedCalls}/{evaluation.totalCalls} completed
                        </span>
                        <span>
                          Reports: {evaluation.reportsGenerated}/{evaluation.totalCalls} generated
                        </span>
                        {evaluation.generatedAt && (
                          <span>Evaluated: {new Date(evaluation.generatedAt).toLocaleDateString()}</span>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      {evaluation.status === "ready" && (
                        <Button
                          onClick={() => handleGenerateFullEvaluation(evaluation)}
                          disabled={generatingFullEvalId === evaluation.employeeId}
                          size="sm"
                          className="gap-2"
                        >
                          {generatingFullEvalId === evaluation.employeeId ? (
                            <>
                              <Loader2 className="h-4 w-4 animate-spin" />
                              Generating...
                            </>
                          ) : (
                            <>
                              <BarChart3 className="h-4 w-4" />
                              Generate Full Evaluation
                            </>
                          )}
                        </Button>
                      )}
                      {evaluation.status === "completed" && (
                        <Button
                          onClick={() => handleViewFullEvaluation(evaluation)}
                          size="sm"
                          variant="default"
                          className="gap-2"
                        >
                          <FileText className="h-4 w-4" />
                          View Full Evaluation
                        </Button>
                      )}
                      {evaluation.status === "in-progress" && (
                        <div className="flex items-center gap-2 text-sm text-muted-foreground">
                          <Loader2 className="h-4 w-4 animate-spin" />
                          Waiting for calls to complete...
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        )}

        <div className="mb-6 grid gap-4 md:grid-cols-2 lg:grid-cols-4">
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Total Customers</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-card-foreground">{statusCounts.total}</h3>
                </div>
                <div className="rounded-lg bg-primary/10 p-3">
                  <Users className="h-6 w-6 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Completed</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-success">{completedCount}</h3>
                </div>
                <div className="rounded-lg bg-success/10 p-3">
                  <Smile className="h-6 w-6 text-success" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">In Progress</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-primary">{inProgressCount}</h3>
                </div>
                <div className="rounded-lg bg-primary/10 p-3">
                  <Loader2 className="h-6 w-6 text-primary" />
                </div>
              </div>
            </CardContent>
          </Card>
          <Card className="bg-card">
            <CardContent className="p-6">
              <div className="flex items-center justify-between">
                <div>
                  <p className="font-sans text-sm font-medium text-muted-foreground">Urgent</p>
                  <h3 className="mt-2 font-sans text-3xl font-bold text-destructive">{urgentCount}</h3>
                </div>
                <div className="rounded-lg bg-destructive/10 p-3">
                  <Frown className="h-6 w-6 text-destructive" />
                </div>
              </div>
            </CardContent>
          </Card>
        </div>

        <Card className="mb-6 bg-card">
          <CardContent className="p-4">
            <div className="flex flex-wrap gap-4">
              <div className="flex-1 min-w-[300px]">
                <div className="relative">
                  <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                  <Input
                    placeholder="Search by customer name or phone number..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-10 font-sans"
                  />
                </div>
              </div>
              <Select value={statusFilter} onValueChange={setStatusFilter}>
                <SelectTrigger className="w-[180px] font-sans">
                  <SelectValue placeholder="All Statuses" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Statuses</SelectItem>
                  <SelectItem value="completed">Completed</SelectItem>
                  <SelectItem value="pending">Pending</SelectItem>
                  <SelectItem value="in-progress">In Progress</SelectItem>
                  <SelectItem value="no-answer">No Answer</SelectItem>
                  <SelectItem value="failed">Failed</SelectItem>
                </SelectContent>
              </Select>
              <Select value={sortFilter} onValueChange={setSortFilter}>
                <SelectTrigger className="w-[180px] font-sans">
                  <SelectValue placeholder="Newest First" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="newest">Newest First</SelectItem>
                  <SelectItem value="oldest">Oldest First</SelectItem>
                </SelectContent>
              </Select>
              <Button variant="outline" className="gap-2 bg-transparent">
                <Loader2 className="h-4 w-4" />
                Export CSV
              </Button>
            </div>
          </CardContent>
        </Card>

        <Card className="bg-card">
          <CardHeader>
            <CardTitle className="font-sans text-xl font-semibold text-card-foreground">
              Customers ({filteredRecords.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <div className="flex h-64 items-center justify-center">
                <Loader2 className="h-8 w-8 animate-spin text-primary" />
              </div>
            ) : filteredRecords.length === 0 ? (
              <div className="flex h-64 items-center justify-center">
                <p className="font-sans text-sm text-muted-foreground">
                  {searchQuery || statusFilter !== "all" ? "No customers match the filters" : "No customers found"}
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <Table>
                  <TableHeader>
                    <TableRow className="border-border hover:bg-transparent">
                      <TableHead className="font-sans font-semibold text-foreground">Customer Name</TableHead>
                      <TableHead className="font-mono text-sm text-muted-foreground">Phone Number</TableHead>
                      <TableHead className="font-sans text-sm text-foreground">Date & Time</TableHead>
                      <TableHead className="font-mono text-sm text-foreground">Duration</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Status</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Customer Mood</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Report</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Score</TableHead>
                      <TableHead className="font-sans font-semibold text-foreground">Notes</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    {filteredRecords.map((record) => (
                      <TableRow key={record.id} className="border-border">
                        <TableCell className="font-sans font-medium text-foreground">{record.customerName}</TableCell>
                        <TableCell className="font-mono text-sm text-muted-foreground">{record.phoneNumber}</TableCell>
                        <TableCell className="font-sans text-sm text-foreground">
                          <div>{record.date}</div>
                          <div className="text-xs text-muted-foreground">{record.time}</div>
                        </TableCell>
                        <TableCell className="font-mono text-sm text-foreground">{record.duration}</TableCell>
                        <TableCell>
                          <Badge variant="outline" className={getStatusBadge(record.status)}>
                            <span className="flex items-center gap-1.5">
                              {getStatusIcon(record.status)}
                              {record.status === "completed"
                                ? "Completed"
                                : record.status === "failed"
                                  ? "Failed"
                                  : record.status === "no-answer"
                                    ? "No Answer"
                                    : record.status === "cancelled"
                                      ? "Cancelled"
                                      : record.status === "pending"
                                        ? "Pending"
                                        : "In Progress"}
                            </span>
                          </Badge>
                        </TableCell>
                        <TableCell>
                          {record.mood && record.hasReport ? (
                            <Badge
                              variant="outline"
                              className={CUSTOMER_MOODS[record.mood as keyof typeof CUSTOMER_MOODS].color}
                            >
                              {CUSTOMER_MOODS[record.mood as keyof typeof CUSTOMER_MOODS].label}
                            </Badge>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          {record.hasReport ? (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="gap-2"
                              onClick={() => router.push(`/reports/${record.id}`)}
                            >
                              <FileText className="h-4 w-4" />
                              View Report
                            </Button>
                          ) : (
                            <Button
                              variant="ghost"
                              size="sm"
                              className="gap-2"
                              onClick={() => handleGenerateReport(record.id, record)}
                              disabled={generatingReportId === record.id || record.status !== "completed"}
                            >
                              {generatingReportId === record.id ? (
                                <>
                                  <Loader2 className="h-4 w-4 animate-spin" />
                                  Generating...
                                </>
                              ) : (
                                <>
                                  <FileText className="h-4 w-4" />
                                  Generate Report
                                </>
                              )}
                            </Button>
                          )}
                        </TableCell>
                        <TableCell>
                          {record.score && record.hasReport ? (
                            <div className="text-center">
                              <div className="text-lg font-bold text-primary">{record.score}/10</div>
                            </div>
                          ) : (
                            <span className="text-xs text-muted-foreground">-</span>
                          )}
                        </TableCell>
                        <TableCell>
                          <Button
                            variant="outline"
                            size="sm"
                            className="gap-2 bg-transparent"
                            onClick={() => handleNotesUpdate(record.id, record.notes || "")}
                          >
                            {record.notes ? (
                              <span className="max-w-[100px] truncate">{record.notes}</span>
                            ) : (
                              "Add Notes"
                            )}
                          </Button>
                        </TableCell>
                      </TableRow>
                    ))}
                  </TableBody>
                </Table>
              </div>
            )}
          </CardContent>
        </Card>
      </main>
      <Dialog open={isNotesDialogOpen} onOpenChange={setIsNotesDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Notes for {editingNotes ? editingNotes.customerName : "Customer"}</DialogTitle>
            <DialogDescription>Add or edit notes for this customer interaction</DialogDescription>
          </DialogHeader>
          <Textarea
            placeholder="Enter notes here..."
            value={editingNotes ? editingNotes.notes : ""}
            onChange={(e) => setEditingNotes({ ...editingNotes!, notes: e.target.value })}
            rows={5}
          />
          <Button onClick={handleSaveNotes} className="mt-4">
            {/* This button should not have a loader by default, only during save */}
            Save Notes
          </Button>
        </DialogContent>
      </Dialog>
    </div>
  )
}
